"*wmNames:				4DWM, CTWM, DXWM, FVWM, GWM, MWM, OLVWM, OLWM, TWM, VTWM, VUEWM",
"*wm_4DWM:				IRIS Extended Motif Window Manager, 4Dwm, .4Dwmrc.%s, -xrm \"4Dwm*configFile: %s\"",
"*wm_CTWM:				Claude's Tab Window Manager, ctwm -n, .twmrc.%s, -f %s",
"*wm_DXWM:				DEC X Window Manager, dxwm",
"*wm_FVWM:				Feeble Virtual Window Manager, fvwm",
"*wm_GWM:				Generic Window Manager, gwm -F, .gwmrc.gwm.%s, -f %s",
"*wm_MWM:				Motif Window Manager, mwm, .mwmrc.%s, -xrm \"mwm*configFile: %s\"",
"*wm_OLVWM:				Open Look Virtual Window Manager, olvwm, .olwmmenu.%s, , OLWMMENU=%s",
"*wm_OLWM:				Open Look Window Manager, olwm, .olwmmenu.%s, , OLWMMENU=%s",
"*wm_TWM:				Tab Window Manager, twm, .twmrc.%s, -f %s",
"*wm_VTWM:				Virtual Tab Window Manager, vtwm, .twmrc.%s, -f %s",
"*wm_VUEWM:				HP VUE Workspace Manager, vuewm, .vue/vuewmrc.%s, -xrm \"vuewm*configFile: %s\"",
"*appNames:				XTerm, Emacs, XEdit, XMan",
"*app_Emacs:				Emacs (Text editor), emacs -i",
"*app_XEdit:				XEdit (Text editor), xedit",
"*app_XMan:				XMan (Manual page), xman -notopbox -bothshown",
"*app_XTerm:				XTerm (Terminal emulator), xterm -ls",
"*lockCommand:				xscreensaver-command -lock",
"*menubox.top:				ChainTop",
"*menubox.bottom:			ChainTop",
"*menubox.left:				ChainLeft",
"*menubox.right:				ChainLeft",
"*menubox.showGrip:			False",
"*ascii_text.width:			650",
"*ascii_text.height:			130",
"*ascii_text.scrollVertical:		whenNeeded",
"*ascii_text.scrollHorizontal:		whenNeeded",
"*ascii_text*translations:		#override\\n\
	Ctrl<KeyPress>C:	Clear()",
"*ascii_text.top:			ChainTop",
"*ascii_text.bottom:			Rubber",
"*ascii_text.left:			ChainLeft",
"*ascii_text.right:			ChainRight",
"*ascii_text*font:			fixed",
"*ascii_text.vertDistance:		0",
"*ascii_text2.width:			650",
"*ascii_text2.height:			130",
"*ascii_text2.scrollVertical:		whenNeeded",
"*ascii_text2.scrollHorizontal:		whenNeeded",
"*ascii_text2*translations:		#override\\n\
	Ctrl<KeyPress>C:	Clear2()",
"*ascii_text2.top:			Rubber",
"*ascii_text2.bottom:			ChainBottom",
"*ascii_text2.left:			ChainLeft",
"*ascii_text2.right:			ChainRight",
"*ascii_text2*font:			fixed",
"*MenuButton.ShapeStyle:			Oval",
"*MenuButton.leftBitmap:			menu12",
"*Command.ShapeStyle:			Oval",
"*session_button.label:			Session",
"*lock_menu_item.label:			Lock",
"*quit_menu_item.label:			Quit",
"*wm_button.label:			Window Managers",
"*none_menu_item.label:			None",
"*app_button.label:			Applications",
"*misc_button.label:			Misc",
"*clear_menu_item.label:			Clear Session Log",
"*clear2_menu_item.label:		Clear Console Log",
"*translations:				#override\\n\
	<Message>WM_PROTOCOLS:	WMProtocols()\\n\
	<UnmapNotify>:		Iconify()\\n\
	<MapNotify>:		Deiconify()",
