#!/bin/ksh
# $XConsortium: run_tests,v 1.0 93/11/22 12:40:58 rws Exp $
#
#
#   (c) Copyright Hewlett-Packard Company, 1993, Fort Collins, Colorado       
#                                                                            
#                             All Rights Reserved                           
#                                                                          
#   Permission to use, copy, modify, and distribute this software and its 
#   documentation for any purpose and without fee is hereby granted,     
#   provided that the above copyright notices appear in all copies and that   
#   both the copyright notices and this permission notice appear in          
#   supporting documentation, and that the name of Hewlett-Packard not be   
#   used in advertising or publicity pertaining to distribution of the     
#   software without specific, written prior permission.                  
#                                                                        
#   HEWLETT-PACKARD MAKES NO WARRANTY OF ANY KIND WITH REGARD TO THIS   
#   SOFTWARE, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  Hewlett-Packard    
#   shall not be liable for errors contained herein or direct, indirect,     
#   special, incidental or consequential damages in connection with the     
#   furnishing, performance or use of this software.                       
#                                                                         
#

unset PAUSE
export HPPEX_DHA_COMPLIANCE_MODE=1

OC_TESTS="errocp.87.1 errocp.87.2 \
          errocp.88.1 errocp.88.2 errocp.88.3 \
	  errocp.88.4 errocp.88.5 errocp.88.6 \
          errocp.89.1 errocp.89.2 \
          errocp.90.1 errocp.90.2 \
          errocp.91.1 errocp.91.2 errocp.91.3 \
          errocp.91.4 errocp.91.5 \
          errocp.92.1 errocp.92.2 errocp.92.3 \
          errocp.93.1 errocp.93.2 errocp.93.3 \
          errocp.94.1 errocp.94.2 errocp.94.3 \
          errocp.94.4 errocp.94.5 errocp.94.6 \
          errocp.95.1 errocp.95.2 errocp.95.3 \
          errocp.96.1 errocp.96.2 \
	  errocp.96.3 errocp.96.4 \
          errocp.97.1 errocp.97.2 errocp.97.3 \
          errocp.97.4 errocp.97.5 errocp.97.6 \
          errocp.97.7 errocp.97.8 errocp.97.9 \
          errocp.97.10 \
          errocp.98.1 errocp.98.2 errocp.98.3 \
          errocp.98.4 errocp.98.5 errocp.98.6 \
          errocp.98.7 errocp.98.8 errocp.98.9 \
          errocp.98.10 \
          errocp.99.1 \
          errocp.100.1 \
          errocp.101.1"

if [ $RUN_IMM = 1 ] 
then 
    REF_IMAGE_DIR=$REF_IMM; export REF_IMAGE_DIR
    CUR_IMAGE_DIR=$CUR_IMM; export CUR_IMAGE_DIR
    BAD_IMAGE_DIR=$BAD_IMM; export BAD_IMAGE_DIR

    echo "\n# Running Immediate Mode Tests"

    for test in $OC_TESTS
    do
	$EXECUTE_TEST $test -i
    done
fi

if [ $RUN_STR = 1 ] 
then 
    REF_IMAGE_DIR=$REF_STR; export REF_IMAGE_DIR
    CUR_IMAGE_DIR=$CUR_STR; export CUR_IMAGE_DIR
    BAD_IMAGE_DIR=$BAD_STR; export BAD_IMAGE_DIR

    echo "\n# Running Structure Mode Tests"

    for test in $OC_TESTS
    do
	$EXECUTE_TEST $test -s

    done
fi

