#undef Boolean
#undef Alignment
#undef Axis
#undef CharCode
#undef Coord
#undef PixelCoord
#undef Tag
#undef Action
#undef ActionImpl
#undef ActionStub
#undef Action_var
#undef ActiveViewer
#undef Adjustment
#undef AdjustmentStub
#undef Adjustment_var
#undef Allocator
#undef ApplicationWindow
#undef ArrowSubclassName
#undef BaseThreadsObj
#undef BaseThreadsObj_var
#undef Beveler
#undef BoundedFloat
#undef Box
#undef Brush
#undef BrushImpl
#undef BrushStub
#undef Brush_var
#undef Button
#undef ButtonImpl
#undef ButtonStub
#undef Button_var
#undef CharString
#undef CharStringBuffer
#undef CharStringImpl
#undef CharStringStub
#undef CharString_var
#undef ClippingStack
#undef Color
#undef ColorImpl
#undef ColorStub
#undef Color_var
#undef ConditionImpl
#undef ConditionVariable
#undef ConditionVariable_var
#undef Cursor
#undef CursorImpl
#undef CursorStub
#undef Cursor_var
#undef Damage
#undef DamageRegion
#undef DamageStub
#undef Damage_var
#undef DebugGlyph
#undef DeckImpl
#undef DefaultPainterImpl
#undef Directory
#undef DirectoryEntry
#undef DirectoryImpl
#undef Display
#undef DisplayImpl
#undef DisplayImplDamage
#undef DisplayImplFilters
#undef DisplayImplRemoveFilter
#undef DisplayImplWindowTable
#undef DisplayStub
#undef Display_var
#undef DrawingKit
#undef DrawingKitColorTable
#undef DrawingKitFontTable
#undef DrawingKitImpl
#undef DrawingKitStub
#undef DrawingKit_var
#undef Event
#undef EventImpl
#undef EventStub
#undef Event_var
#undef Figure
#undef FigureKit
#undef FigureKitImpl
#undef FigureKitStub
#undef FigureKit_var
#undef FigureLabel
#undef FigureStyle
#undef FigureStyleImpl
#undef FigureStyleStub
#undef FigureStyle_var
#undef File
#undef FileInfo
#undef Focus
#undef FocusImpl
#undef FocusStub
#undef Focus_var
#undef Font
#undef FontImpl
#undef FontSpec
#undef FontStub
#undef Font_var
#undef Fresco
#undef FrescoImpl
#undef FrescoObject
#undef FrescoObjectStub
#undef FrescoObject_var
#undef GTStack
#undef GenericSequence
#undef Glue
#undef Glyph
#undef GlyphImpl
#undef GlyphOffset
#undef GlyphOffsetStub
#undef GlyphOffset_var
#undef GlyphStub
#undef GlyphTraversal
#undef GlyphTraversalImpl
#undef GlyphTraversalStub
#undef GlyphTraversal_var
#undef Glyph_var
#undef HStrut
#undef Host
#undef IconWindow
#undef InputFile
#undef LayoutAlign
#undef LayoutCenter
#undef LayoutFixed
#undef LayoutKit
#undef LayoutKitImpl
#undef LayoutKitStub
#undef LayoutKit_var
#undef LayoutLayer
#undef LayoutManager
#undef LayoutMargin
#undef LayoutNatural
#undef LayoutSuperpose
#undef LayoutTile
#undef LayoutTileFirstAligned
#undef LayoutTileReversed
#undef LayoutTileReversedFirstAligned
#undef LayoutVariable
#undef List
#undef LockImpl
#undef LockObj
#undef LockObj_var
#undef LockedFrescoObjectImpl
#undef MainViewer
#undef ManagedWindow
#undef Math
#undef MatrixStack
#undef MatrixStackElement
#undef Memory
#undef Menu
#undef MenuItem
#undef MenuItemStub
#undef MenuItem_var
#undef MenuStub
#undef Menu_var
#undef MonoGlyph
#undef MonoGlyphOffset
#undef ObservableInfo
#undef ObserverList
#undef Option
#undef Painter
#undef PainterStub
#undef Painter_var
#undef Pattern
#undef PatternImpl
#undef PatternStub
#undef Pattern_var
#undef PickTraversal
#undef Placement
#undef PolyFigure
#undef PolyGlyph
#undef PolyGlyphOffset
#undef PopupWindow
#undef PtrList
#undef RGBTable
#undef Raster
#undef RasterBitmap
#undef RasterChannels
#undef RasterImpl
#undef RasterLUT
#undef RasterStub
#undef Raster_var
#undef Region
#undef RegionImpl
#undef RegionStub
#undef Region_var
#undef Screen
#undef ScreenImpl
#undef ScreenStub
#undef ScreenVisualList
#undef Screen_var
#undef Semaphore
#undef SemaphoreImpl
#undef Semaphore_var
#undef ShapeOf
#undef SharedFrescoObjectImpl
#undef SharedStyleImpl
#undef Slider
#undef SliderViewer
#undef Space
#undef StdInput
#undef Stepper
#undef StepperSubclassName
#undef Strut
#undef Style
#undef StyleCloner
#undef StyleData
#undef StyleImpl
#undef StyleList
#undef StyleMatcher
#undef StyleStub
#undef StyleValue
#undef StyleValueImpl
#undef StyleValueImplList
#undef StyleValueStub
#undef StyleValueTable
#undef StyleValueTableEntry
#undef StyleValue_var
#undef StyleVisitor
#undef StyleVisitorImpl
#undef StyleVisitorStub
#undef StyleVisitor_var
#undef Style_var
#undef Table
#undef Table2
#undef Telltale
#undef TelltaleImpl
#undef TelltaleStub
#undef Telltale_var
#undef ThreadImpl
#undef ThreadKit
#undef ThreadKitImpl
#undef ThreadKit_var
#undef ThreadList
#undef ThreadObj
#undef ThreadObj_var
#undef TopLevelWindow
#undef Transform
#undef TransformAllocator
#undef TransformImpl
#undef TransformStub
#undef Transform_var
#undef TransientWindow
#undef VStrut
#undef Vertex
#undef Viewer
#undef ViewerImpl
#undef ViewerOffset
#undef ViewerStub
#undef Viewer_var
#undef VisualTable
#undef WKButtonFrame
#undef WKCheckmark
#undef WKDefaultArrow
#undef WKFrame
#undef WKGlyph
#undef WKIndicator
#undef WKMenuItemFrame
#undef WKPushButtonFrame
#undef WKRadioFlag
#undef WKRadioItem
#undef WKThumb
#undef WidgetKit
#undef WidgetKitImpl
#undef WidgetKitStub
#undef WidgetKit_var
#undef Window
#undef WindowImpl
#undef WindowStub
#undef WindowStyle
#undef WindowStyle_var
#undef Window_var
#undef XPainterImpl
#undef XSlider
#undef XYSlider
#undef YSlider
