#! /bin/csh -f
# Copyright 1985, Massacusetts Institute of Technology.
set prntr=(-Pln03)
set flags=() noglob
unset dv
unsetenv dv
set dv=""
top:
	if ($#argv > 0) then
		switch ($argv[1])

		case -display:
			set dv="-display $argv[2]"
			shift argv
			shift argv
			goto top

		case -P?*:
			set prntr = $argv[1]
			shift argv
			goto top

		case *:
			set flags = ($flags $argv[1])
			shift argv
			goto top

		endsw
	endif
xwd $dv | xpr $flags | lpr $prntr
