#Makefile to build OpenLook atom mapping library.
#


all:
	cc -o libatommap.so.1.1 -Xc -O -K pic -G -L/usr/openwin/lib -I.. -I/usr/openwin/include -DSYSV -DXMOVE -DNeedFunctionPrototypes=1 -DDEBUG -DSVR4 -DSYSV -Dsun libatommap.c
	rm -f libatommap.so.1
	ln -s libatommap.so.1.1 libatommap.so.1

clean: 
	- rm -rf *.so* *~ \#*
