#!/bin/ksh
# $XConsortium: run_tests,v 1.0 93/11/22 12:29:07 rws Exp $
#
#
#   (c) Copyright Hewlett-Packard Company, 1993, Fort Collins, Colorado       
#                                                                            
#                             All Rights Reserved                           
#                                                                          
#   Permission to use, copy, modify, and distribute this software and its 
#   documentation for any purpose and without fee is hereby granted,     
#   provided that the above copyright notices appear in all copies and that   
#   both the copyright notices and this permission notice appear in          
#   supporting documentation, and that the name of Hewlett-Packard not be   
#   used in advertising or publicity pertaining to distribution of the     
#   software without specific, written prior permission.                  
#                                                                        
#   HEWLETT-PACKARD MAKES NO WARRANTY OF ANY KIND WITH REGARD TO THIS   
#   SOFTWARE, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF 
#   MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  Hewlett-Packard    
#   shall not be liable for errors contained herein or direct, indirect,     
#   special, incidental or consequential damages in connection with the     
#   furnishing, performance or use of this software.                       
#                                                                         
#

unset PAUSE

NON_OC_TESTS="nms-invis1 \
              nms-invis2 \
              nms-invis3 \
              nms-highl1 \
              nms-highl2 \
              nms-highl3 \
	      nms-addrm1 \
	      nms-addrm2"

FULL_TESTS="nms-pick1  \
            nms-pick2  \
            nms-pick3"

if [ $RUN_NOC = 1 ]
then

    REF_IMAGE_DIR=$REF_NOC; export REF_IMAGE_DIR
    CUR_IMAGE_DIR=$CUR_NOC; export CUR_IMAGE_DIR
    BAD_IMAGE_DIR=$BAD_NOC; export BAD_IMAGE_DIR

    echo "\n# Running Non-OC Tests"

    for test in $NON_OC_TESTS
    do
        $EXECUTE_TEST $test -n
    done

    if [ $RUN_FULL = 1 ]
    then
        for test in $FULL_TESTS
        do
            $EXECUTE_TEST $test -n
        done
    fi
fi

