.\" $Id: youbin_sub.man,v 4.1 1994/05/31 08:44:02 yamamoto Exp $
.TH YOUBIN_SUB 3 "1993年9月26日"
.SH "名前"
youbin_sub \- youbinプロトコルのクライアント用交信ライブラリ
.SH "形式"
.nf
.ft B
#include <local/youbin.h>
.ft
.fi
.LP
.nf
.ft B
youbin_sub(server_name, option_list, user_func, file_id)
char  *server_name;
char  *option_list;
void  (*user_func)(size, date, mess);
int   file_id;
.ft
.fi
.SH "機能説明"
.BR youbin_sub
は郵便プロトコルで交信するクライアントプログラムのためのイン
タフェースである．この関数に制御がわたると郵便サーバとの交信が切れるま
で，呼び出しルーチンに制御は戻らない．youbin_subはserver_nameで指定
されたサーバホストに，プログラムを起動したユーザー名を持って接続を要求
する．接続が完了してユーザーのメールスプールの監視が始まると，スプール
の状態が変化した時，および一定の時間間隔で，スプール状態がサーバから知ら
される．youbin_subは受けとった情報をuser_funcを通して，呼び出しルー
チンに知らせる．この時，第1引数はスプールのサイズ，第2引数はスプール
の変更時刻，第3引数はメール到着時ヘッダーおよび最初の数行のメール内容で
ある．スプールが読み出された時と，定期的なチェック時には，空文字列への
ポインタ("")
が返される．また，ヘッダー等の情報が必要かどうかはoption_listで指定
される．user_funcは必ずしもスプール変化がない時も起動されるので，直前
に呼ばれた時のsizeおよびdateを保存し，呼び出しが定期的なものであるの
か，スプールの変化によるものかを調べる必要がある．
.LP
youbin_subに制御を渡した後でyoubin_subに情報を渡すには，file_idで指
定したファイル番号に書き込む．渡す情報としては，"Update"はスプール状
態の再チェックを要求する．これはスプールから読み出しを行なったことを明
示的に知らせ，スプール状態の変化をサーバに知らせるために用意されている．
"Quit"はクライアントの終了を知らせるためである．サーバーは一定時間内
にクライアントからの応答がない時には，接続を終了するので必ずしも
"Quit"を送って終了を知らせる必要はない．youbin_subにこれらの情報を送
る必要がない時にはfile_idには-1を指定する．
.LP
現在，オプションとして用意されているのは"Debug"と"Biff"である．両
方を指定する時は，"Debug,Biff"(順番はどちらでも良い)とする．Debug
が指定されると，サーバとのやりとりのパケット内容が表示される．Biffが
指定されると，メールの到着時にuser_funcの第3引数にヘッダー等の情報
が送られる．
.LP
.SH 戻り値
正常終了すると0が返され，エラーの時には次の値が返される．
.RS
.LP
.nf
.ta \w'ERR_SERVICE 'u +w'15*  'u
\fB\s-1ERR_USER		1  :	ユーザー名が登録されていない．
\fB\s-1ERR_HOST		2  : 指定されたサーバが登録されていない．
\fB\s-1ERR_SERVICE	3  : サービス(一般には "biff")が登録されていない．
\fB\s-1ERR_SOCKET	4  : ソケットがオープンできない．
\fB\s-1ERR_BIND		5  : ソケットにバインドできない．
\fB\s-1ERR_NAK		6  : サーバに接続を拒否された．
\fB\s-1ERR_RTRY		7  : サーバからの応答がない．
\fB\s-1RET_QUIT		91 : サーバから終了する旨通知があった．
.fi
.SH "関連項目"
.BR youbin(1),
.BR youbind(1),
.BR xyoubin(1)
