.\" $Id: youbind.man,v 4.2 1994/06/12 09:34:35 yamamoto Exp $
.TH YOUBIND 8 "1993年9月26日"
.SH "名前"
youbind \- youbinサービスのサーバ
.SH "形式"
.B youbind
[
.B \-d
][
.B \-h
][
.B \-A port
]
.SH "機能説明"
youbindは郵便プロトコルのサーバです．郵便プロトコルはネットワーク時代
に対応したbiffプロトコルであり，これまでのbiffに上位互換性を持ちま
す．youbindはクライアントからの要求を受け付け，
クライアントの指定するユーザのメールスプールを監視します．メールスプー
ルの変化が認められると，クライアントにその旨を通知します．また，クライ
アントと定期的な交信を行ない，その接続状態を維持管理します．スプールへ
の書き込みは/bin/mailからの，biffパケットを受信することで見つけま
す．スプールからの読み出しは，規定時間毎のチェックで見つけますが，サー
バの負荷を軽くするためにこの時間はかなり長いものとしています．そのため，
読み出しをすると，サーバに読み出したことを知らせることが求められます．
多くのサイトではPOPとの併用がなされるものと考え，POPで読み出した
時にyoubindに知らせるよう改造されたPOPも用意されています．また，
emacsのmh-eを使っている人にはこのためのmh-inc-hookを用意していま
す．

.SH "オプション"
\-d オプションが指定されると各種のデバッグ情報を出力します．この中には
クライアントとの交信の様子，クライアントの登録，抹消，及びその状態の変
化などが含まれます．
.LP
\-h オプションが指定されると youbind の簡単な説明が出力されます．
.LP
-A port オプションが指定されると，youbind は biff ポートの他に port ポー
トからのパケットも受け取ります．これは biff ポート以外のポートを使って
メールの到着を知らせている機械のためのものです．今までのところＭＩＰＳ
社の機械では mbiff ポートが使われていることが分かっています．
.SH "関連ファイル"
.BR /usr/spool/mail	メールスプールディレクトリ
.SH "関連事項"
.BR biff(1),
.BR youbin(1),
.BR xyoubin(1),

.SH "バグ"
.B 郵便サーバーに登録できるユーザーの数は256人です．郵便クライアントの数
は1024までです．
