LIBRARY XTST
VERSION LIBRARY_VERSION
EXPORTS
 XTestCompareCurrentCursorWithWindow
 XTestCompareCursorWithWindow
 XTestDiscard
 XTestFakeButtonEvent
 XTestFakeDeviceButtonEvent
 XTestFakeDeviceKeyEvent
 XTestFakeDeviceMotionEvent
 XTestFakeKeyEvent
 XTestFakeMotionEvent
 XTestFakeProximityEvent
 XTestFakeRelativeMotionEvent
 XTestGrabControl
 XTestQueryExtension
 XTestSetGContextOfGC
 XTestSetVisualIDOfVisual
