
/* $XConsortium: xlib.k,v 5.2 94/04/17 20:46:45 rws Exp $ */

/*****************************************************************

Copyright (c) 1989, 1990, 1991,1990  X Consortium

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
X CONSORTIUM BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Except as contained in this notice, the name of the X Consortium shall not be
used in advertising or otherwise to promote the sale, use or other dealings
in this Software without prior written authorization from the X Consortium.

Copyright (c) 1989, 1990, 1991,1990 by Sun Microsystems, Inc.

                        All Rights Reserved

Permission to use, copy, modify, and distribute this software and its 
documentation for any purpose and without fee is hereby granted, 
provided that the above copyright notice appear in all copies and that
both that copyright notice and this permission notice appear in 
supporting documentation, and that the names of Sun Microsystems,
and the X Consortium, not be used in advertising or publicity 
pertaining to distribution of the software without specific, written 
prior permission.  

SUN MICROSYSTEMS DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE, 
INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS, IN NO EVENT 
SHALL SUN MICROSYSTEMS BE LIABLE FOR ANY SPECIAL, INDIRECT OR CONSEQUENTIAL 
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
SOFTWARE.

******************************************************************/


None
ParentRelative
CopyFromParent
PointerWindow
InputFocus
PointerRoot
AnyPropertyType
AnyKey
AnyButton
AllTemporary
CurrentTime
NoSymbol
NoEventMask
KeyPressMask
KeyReleaseMask
ButtonPressMask
ButtonReleaseMask
EnterWindowMask
LeaveWindowMask
PointerMotionMask
PointerMotionHintMask
Button1MotionMask
Button2MotionMask
Button3MotionMask
Button4MotionMask
Button5MotionMask
ButtonMotionMask
KeymapStateMask
ExposureMask
VisibilityChangeMask
StructureNotifyMask
ResizeRedirectMask
SubstructureNotifyMask
SubstructureRedirectMask
FocusChangeMask
PropertyChangeMask
ColormapChangeMask
OwnerGrabButtonMask
KeyPress
KeyRelease
ButtonPress
ButtonRelease
MotionNotify
EnterNotify
LeaveNotify
FocusIn
FocusOut
KeymapNotify
Expose
GraphicsExpose
NoExpose
VisibilityNotify
CreateNotify
DestroyNotify
UnmapNotify
MapNotify
MapRequest
ReparentNotify
ConfigureNotify
ConfigureRequest
GravityNotify
ResizeRequest
CirculateNotify
CirculateRequest
PropertyNotify
SelectionClear
SelectionRequest
SelectionNotify
ColormapNotify
ClientMessage
MappingNotify
LASTEvent
ShiftMask
LockMask
ControlMask
Mod1Mask
Mod2Mask
Mod3Mask
Mod4Mask
Mod5Mask
ShiftMapIndex
LockMapIndex
ControlMapIndex
Mod1MapIndex
Mod2MapIndex
Mod3MapIndex
Mod4MapIndex
Mod5MapIndex
Button1Mask
Button2Mask
Button3Mask
Button4Mask
Button5Mask
AnyModifier
Button1
Button2
Button3
Button4
Button5
NotifyNormal
NotifyGrab
NotifyUngrab
NotifyWhileGrabbed
NotifyHint
NotifyAncestor
NotifyVirtual
NotifyInferior
NotifyNonlinear
NotifyNonlinearVirtual
NotifyPointer
NotifyPointerRoot
NotifyDetailNone
VisibilityUnobscured
VisibilityPartiallyObscured
VisibilityFullyObscured
PlaceOnTop
PlaceOnBottom
FamilyInternet
FamilyDECnet
FamilyChaos
PropertyNewValue
PropertyDelete
ColormapUninstalled
ColormapInstalled
GrabModeSync
GrabModeAsync
GrabSuccess
AlreadyGrabbed
GrabInvalidTime
GrabNotViewable
GrabFrozen
AsyncPointer
SyncPointer
ReplayPointer
AsyncKeyboard
SyncKeyboard
ReplayKeyboard
AsyncBoth
SyncBoth
RevertToNone
RevertToPointerRoot
RevertToParent
Success
BadRequest
BadValue
BadWindow
BadPixmap
BadAtom
BadCursor
BadFont
BadMatch
BadDrawable
BadAccess
BadAlloc
BadColor
BadGC
BadIDChoice
BadName
BadLength
BadImplementation
FirstExtensionError
LastExtensionError
InputOutput
InputOnly
CWBackPixmap
CWBackPixel
CWBorderPixmap
CWBorderPixel
CWBitGravity
CWWinGravity
CWBackingStore
CWBackingPlanes
CWBackingPixel
CWOverrideRedirect
CWSaveUnder
CWEventMask
CWDontPropagate
CWColormap
CWCursor
CWX
CWY
CWWidth
CWHeight
CWBorderWidth
CWSibling
CWStackMode
ForgetGravity
NorthWestGravity
NorthGravity
NorthEastGravity
WestGravity
CenterGravity
EastGravity
SouthWestGravity
SouthGravity
SouthEastGravity
StaticGravity
UnmapGravity
NotUseful
WhenMapped
Always
IsUnmapped
IsUnviewable
IsViewable
SetModeInsert
SetModeDelete
DestroyAll
RetainPermanent
RetainTemporary
Above
Below
TopIf
BottomIf
Opposite
RaiseLowest
LowerHighest
PropModeReplace
PropModePrepend
PropModeAppend
GXclear
GXand
GXandReverse
GXcopy
GXandInverted
GXnoop
GXxor
GXor
GXnor
GXequiv
GXinvert
GXorReverse
GXcopyInverted
GXorInverted
GXnand
GXset
LineSolid
LineOnOffDash
LineDoubleDash
CapNotLast
CapButt
CapRound
CapProjecting
JoinMiter
JoinRound
JoinBevel
FillSolid
FillTiled
FillStippled
FillOpaqueStippled
EvenOddRule
WindingRule
ClipByChildren
IncludeInferiors
Unsorted
YSorted
YXSorted
YXBanded
CoordModeOrigin
CoordModePrevious
Complex
Nonconvex
Convex
ArcChord
ArcPieSlice
GCFunction
GCPlaneMask
GCForeground
GCBackground
GCLineWidth
GCLineStyle
GCCapStyle
GCJoinStyle
GCFillStyle
GCFillRule
GCTile
GCStipple
GCTileStipXOrigin
GCTileStipYOrigin
GCFont
GCSubwindowMode
GCGraphicsExposures
GCClipXOrigin
GCClipYOrigin
GCClipMask
GCDashOffset
GCDashList
GCArcMode
GCLastBit
FontLeftToRight
FontRightToLeft
FontChange
XYBitmap
XYPixmap
ZPixmap
AllocNone
AllocAll
DoRed
DoGreen
DoBlue
CursorShape
TileShape
StippleShape
AutoRepeatModeOff
AutoRepeatModeOn
AutoRepeatModeDefault
LedModeOff
LedModeOn
KBKeyClickPercent
KBBellPercent
KBBellPitch
KBBellDuration
KBLed
KBLedMode
KBKey
KBAutoRepeatMode
MappingSuccess
MappingBusy
MappingFailed
MappingModifier
MappingKeyboard
MappingPointer
DontPreferBlanking
PreferBlanking
DefaultBlanking
DisableScreenSaver
DisableScreenInterval
DontAllowExposures
AllowExposures
DefaultExposures
ScreenSaverReset
ScreenSaverActive
HostInsert
HostDelete
EnableAccess
DisableAccess
StaticGray
GrayScale
StaticColor
PseudoColor
TrueColor
DirectColor
LSBFirst
MSBFirst

